services:
  remembr:
    image: registry.cn-hangzhou.aliyuncs.com/kevinlad/remembr:latest
    container_name: remembr
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    user: appuser
    ipc: host
    pid: host
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
      # Add your OpenAI API key here if needed
      - OPENAI_API_KEY=xxx
      - OPENAI_BASE_URL=https://api.openai.com/v1
    stdin_open: true
    tty: true